---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - git
        - htop
        - tmux
        - neovim
        - colordiff
        - curl
        - at
        - htop
        - iotop
        - lsof
        - mc
        - neofetch
        - net-tools
        - nmap
        - rsync
        - screen
        - wget
        - whois
        - zsh

  - name: add ansible user
    user:
      name: velociraptor
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible cron job
    cron:
      name: ansible auto-provision
      user: velociraptor
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/FifthCard/ansible-desktop.git

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/fifthcard/.bashrc
      owner: fifthcard
      group: fifthcard

  - name: create config dir user fifthcard
    tags: dotfiles, fifthcard,tmux,users,vim,zsh
    file:
      path: /home/fifthcard/{{ item.dir }}
      state: directory
      owner: fifthcard
      group: fifthcard
      mode: 0700
    with_items:
      - { dir: '.bash' }
      - { dir: '.config' }
      - { dir: '.config/nvim' }
      - { dir: '.local' }
      - { dir: '.local/share' }
      - { dir: '.local/share/nvim' }
      - { dir: '.local/share/nvim/site' }
      - { dir: '.local/share/nvim/site/autoload' }
      - { dir: '.zsh' }
      - { dir: '.oh-my-zsh' }
      - { dir: '.oh-my-zsh/custom/' }
      - { dir: '.oh-my-zsh/custom/themes/' }
      - { dir: '.oh-my-zsh/custom/themes/powerlevel10k/' }
      - { dir: '.oh-my-zsh/custom/themes/powerlevel10k/internal/' }

  - name: clone oh-my-zsh for users
    tags:
      - skip_ansible_lint
    command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh'
    args:
      chdir: '~'
      creates: '~/.oh-my-zsh'

  - name: oh-my-zsh powerlevel10k theme
    tags:
      - skip_ansible_lint
    command: 'git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k'

  - name: oh-my-zsh autosuggestion
    tags:
      - skip_ansible_lint
    command: 'git clone -c core.autocrlf=input https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions'


  - name: set permissions of oh-my-zsh for users
    file:
      path: '~/.oh-my-zsh'
      mode: 'go-w'

  - name: users | fifthcard | copy dotfiles
    tags: dotfiles,users,fifthcard,tmux,users,vim,zsh
    copy:
      src: files/fifthcard/{{ item.src }}
      dest: /home/fifthcard/{{ item.dest }}
      owner: fifthcard
      group: fifthcard
      mode: 0600
    with_items:
      - { src: 'bash/bash_aliases', dest: '.bash/bash_aliases' }
      - { src: 'bash/bash_profile', dest: '.bash_profile' }
      - { src: 'bash/bashrc', dest: '.bashrc' }
      - { src: 'bash/profile', dest: '.profile' }
      - { src: 'git/gitconfig', dest: '.gitconfig' }
      - { src: 'nvim/init.vim', dest: '.config/nvim/init.vim' }
      - { src: 'nvim/plug.vim', dest: '.local/share/nvim/site/autoload/plug.vim' }
      - { src: 'zsh/zshrc', dest: '.zshrc' }
      - { src: 'oh-my-zsh/aliases', dest: '.oh-my-zsh/custom/aliases.zsh' }
      - { src: 'oh-my-zsh/p10k.zsh', dest: '.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh' }
      - { src: 'oh-my-zsh/worker.zsh', dest: '.oh-my-zsh/custom/themes/powerlevel10k/internal/worker.zsh' }
      - { src: 'oh-my-zsh/parser.zsh', dest: '.oh-my-zsh/custom/themes/powerlevel10k/internal/parser.zsh' }
      - { src: 'oh-my-zsh/icons.zsh', dest: '.oh-my-zsh/custom/themes/pwoerlevel10k/internal/icons.zsh' }
      - { src: 'oh-my-zsh/configure.zsh', dest: '.oh-my-zsh/custom/themes/pwoerlevel10k/internal/configure.zsh' }


#    notify: update_vim_bundle_perms



