---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux
        - neovim
        - colordiff
        - curl
        - at
        - htop
        - iotop
        - lsof
        - mc
        - neofetch
        - net-tools
        - nmap
        - rsync
        - screen
        - wget
        - whois
        - zsh

  - name: add ansible user
    user:
      name: velociraptor
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible cron job
    cron:
      name: ansible auto-provision
      user: velociraptor
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/FifthCard/ansible-desktop.git

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/fifthcard/.bashrc
      owner: fifthcard
      group: fifthcard

  - name: create config dir user fifthcard
    tags: dotfiles, fifthcard,tmux,users,vim,zsh
    file:
      path: /home/fifthcard/{{ item.dir }}
      state: directory
      owner: fifthcard
      group: fifthcard
      mode: 0700
    with_items:
      - { dir: '.bash' }
      - { dir: '.config' }
      - { dir: '.config/htop' }
      - { dir: '.config/mc' }
      - { dir: '.tmux' }
      - { dir: '.config/nvim' }
      - { dir: '.local' }
      - { dir: '.local/share' }
      - { dir: '.local/share/nvim' }
      - { dir: '.local/share/nvim/site' }
      - { dir: '.local/share/nvim/site/autoload' }
      - { dir: '.tmux/config' }
      - { dir: '.vim' }
      - { dir: '.vim/autoload' }
      - { dir: '.vim/undodir' }
      - { dir: '.zsh' }

  - name: users | fifthcard | copy dotfiles
    tags: dotfiles,users,fifthcard,tmux,users,vim,zsh
    copy:
      src: files/fifthcard/{{ item.src }}
      dest: /home/fifthcard/{{ item.dest }}
      owner: fifthcard
      group: fifthcard
      mode: 0600
    with_items:
      - { src: 'bash/bash_aliases', dest: '.bash/bash_aliases' }
      - { src: 'bash/bash_profile', dest: '.bash_profile' }
      - { src: 'bash/bash_prompt', dest: '.bash/bash_prompt' }
      - { src: 'bash/bash_functions', dest: '.bash/bash_functions' }
      - { src: 'bash/bashrc', dest: '.bashrc' }
      - { src: 'bash/profile', dest: '.profile' }
#      - { src: 'git/gitconfig', dest: '.gitconfig' }
      - { src: 'htop/htoprc', dest: '.config/htop/htoprc' }
      - { src: 'vim/vimrc', dest: '.vimrc' }
      - { src: 'zsh/zshrc', dest: '.zshrc' }
      - { src: 'nvim/init.vim', dest: '.config/nvim/init.vim' }
      - { src: 'nvim/plug.vim', dest: '.local/share/nvim/site/autoload/plug.vim' }


  - name: users | fifthcard | copy individual zsh config files
    tags: dotfiles,fifthcard,users,zsh
    copy:
      src: files/fifthcard/zsh/{{ item.src }}
      dest: /home/fifthcard/.zsh/{{ item.src }}
      owner: fifthcard
      group: fifthcard
      mode: 0600
    with_items:
      - { src: 'aliases.zsh' }
      - { src: 'bindkey.zsh' }
      - { src: 'completion.zsh' }
      - { src: 'exports.zsh' }
      - { src: 'functions.zsh' }
      - { src: 'history.zsh' }
      - { src: 'path.zsh' }
      - { src: 'plugins.zsh' }
      - { src: 'prompt.zsh' }
      - { src: 'setopt.zsh' }
      - { src: 'theming.zsh' }

#    notify: update_vim_bundle_perms



